pyside6-uic forms/main_window.ui -o main_window.py
pyside6-uic forms/open_folder_window.ui -o open_folder_window.py
pyside6-uic forms/open_url_window.ui -o open_url_window.py
pyside6-uic forms/settings_window.ui -o settings_window.py
pyside6-uic forms/about_window.ui -o about_window.py
pyside6-uic forms/screenshot_window.ui -o screenshot_window.py
pyside6-uic forms/reference_window.ui -o reference_window.py
pyside6-uic forms/launch_parameters_window.ui -o launch_parameters_window.py
pyside6-uic forms/android_config_window.ui -o android_config_window.py